### ISSUE TITLE
hi ，your works is great 。 how to use yoloV8 control the uav？

### ISSUE THREAD

**Issue by deepuav** [TPODAvia/PX4-Autonomous-Vehicle#7]

**Comment by TPODAvia** [comment]
Hi!
I'm trying to implement the [Follow Me mode](https://docs.px4.io/main/en/flight_modes/follow_me.html) for uav. 
The plan is to use yolov8_node, extract the information and pass it on to Mavros to control the drone.
But this project is still raw. If you have an idea, I will be happy to help me with this project :)

**Comment by deepuav** [comment]
ok i wait for test .if i  have some code i will   Pull requests it

**Comment by TPODAvia** [comment]
Follow me mode implemented.
