### ISSUE TITLE
can you make 3d lidar ins

### ISSUE THREAD

**Issue by deepuav** [TPODAvia/PX4-Autonomous-Vehicle#9]
Can you replace the visual depth sensor of the PX4-Avoidance/local_planner with 3D LiDAR sensing? I can provide 200m 125 line RS-M1 Lidar and ROS SDK

**Comment by TPODAvia** [comment]
@deepuav Hi, yes, I can replace the visual depth sensor of the PX4-Avoidance/local_planner with 3D LiDAR sensing. The easiest workaround is to convert the point cloud data to the depth image data. More complicated methods seems need to dig into code lines.
https://github.com/TPODAvia/PX4-Autonomous-Vehicle/blob/main/px4_ground/src/point_cloud_to_depth_image.py
